In [93]:
import numpy as np
import pandas as pd
import random
import matplotlib.pyplot as plt

def sigmoid(x):
    y = 1 / (1 + np.exp(-x))
    
    return(y)

def softmax(x):
    ex = np.exp(x)
    return ex / np.sum(ex)

# MultiClass

In [126]:
def MultiClass(W1,W2,X,D):
    alpha = 0.9
    n = 5
    for k in range(n):
        x_k = X[:,:, k].reshape(25,1)
        d_k = D[k,:].T

        v1 = np.dot(x_k.T , W1.T)
        y1 = sigmoid(v1)
        v = np.dot(y1, W2.T)
        y = softmax(v)

        e = d_k - y
        delta = e

        e1 = np.dot(delta, W2)
        delta1 = y1 * (1 - y1) * e1

        dw1 = alpha * np.dot(x_k, delta1)
        W1 = W1 + dw1.T

        dw2 = alpha * np.dot(delta.T, y1)
        W2 = W2 + dw2
    return(W1, W2)

In [136]:
import numpy as np

X = np.zeros((5, 5, 5))
X[:, :, 0] = np.array([[0, 1, 1, 0, 0],
                       [0, 0, 1, 0, 0],
                       [0, 0, 1, 0, 0],
                       [0, 0, 1, 0, 0],
                       [0, 1, 1, 1, 0]])
X[:, :, 1] = np.array([[1, 1, 1, 1, 0],
                       [0, 0, 0, 0, 1],
                       [0, 1, 1, 1, 0],
                       [1, 0, 0, 0, 0],
                       [1, 1, 1, 1, 1]])
X[:, :, 2] = np.array([[1, 1, 1, 1, 0],
                       [0, 0, 0, 0, 1],
                       [0, 1, 1, 1, 0],
                       [0, 0, 0, 0, 1],
                       [1, 1, 1, 1, 0]])
X[:, :, 3] = np.array([[0, 0, 0, 1, 0],
                       [0, 0, 1, 1, 0],
                       [0, 1, 0, 1, 0],
                       [1, 1, 1, 1, 1],
                       [0, 0, 0, 1, 0]])
X[:, :, 4] = np.array([[1, 1, 1, 1, 1],
                       [1, 0, 0, 0, 0],
                       [1, 1, 1, 1, 0],
                       [0, 0, 0, 0, 1],
                       [1, 1, 1, 1, 0]])

D = np.eye(5)

W1 = 2 * np.random.rand(50, 25) - 1
W2 = 2 * np.random.rand(5, 50) - 1

for epoch in range(10000):
    W1, W2 = MultiClass(W1, W2, X, D)
    
N = 5
predict = np.array([])

for k in range(N):
    x_k = X[:,:, k].reshape(25,1)
    v1 = np.dot(x_k.T , W1.T)
    y1 = sigmoid(v1)
    v = np.dot(y1, W2.T)
    y = softmax(v)
    predict = np.append(predict, y)
    
predict

array([1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1.])

In [137]:
predict.reshape(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Test MultiClass

In [138]:
X = np.zeros((5, 5, 5))
X[:, :, 0] = np.array([[0, 0, 1, 1, 0],
                       [0, 0, 1, 1, 0],
                       [0, 1, 0, 1, 0],
                       [0, 0, 0, 1, 0],
                       [0, 1, 1, 1, 0]])
X[:, :, 1] = np.array([[1, 1, 1, 1, 0],
                       [0, 0, 0, 0, 1],
                       [0, 1, 1, 1, 0],
                       [1, 0, 0, 0, 1],
                       [1, 1, 1, 1, 1]])
X[:, :, 2] = np.array([[1, 1, 1, 1, 0],
                       [0, 0, 0, 0, 1],
                       [0, 1, 1, 1, 0],
                       [1, 0, 0, 0, 1],
                       [1, 1, 1, 1, 0]])
X[:, :, 3] = np.array([[0, 1, 1, 1, 0],
                       [0, 1, 0, 0, 0],
                       [0, 1, 1, 1, 0],
                       [0, 0, 0, 1, 0],
                       [0, 1, 1, 1, 0]])
X[:, :, 4] = np.array([[0, 1, 1, 1, 1],
                       [0, 1, 0, 0, 0],
                       [0, 1, 1, 1, 0],
                       [0, 0, 0, 1, 1],
                       [1, 1, 1, 1, 0]])

N = 5
predict = np.array([])

for k in range(N):
    x_k = X[:,:, k].reshape(25,1)
    v1 = np.dot(x_k.T , W1.T)
    y1 = sigmoid(v1)
    v = np.dot(y1, W2.T)
    y = softmax(v)
    predict = np.append(predict, y)
    
predict

array([0. , 0. , 0. , 1. , 0. , 0. , 1. , 0. , 0. , 0. , 0. , 0. , 1. ,
       0. , 0. , 0.1, 0.5, 0.2, 0.2, 0. , 0. , 0. , 0. , 0. , 1. ])

In [139]:
predict.reshape(5,5)

array([[0. , 0. , 0. , 1. , 0. ],
       [0. , 1. , 0. , 0. , 0. ],
       [0. , 0. , 1. , 0. , 0. ],
       [0.1, 0.5, 0.2, 0.2, 0. ],
       [0. , 0. , 0. , 0. , 1. ]])